## Basic classes, int / float / str / list

In [17]:
a = 1; print(type(a))

<class 'int'>


In [18]:
a = 1; a = float(a); print(type(a))

<class 'float'>


In [19]:
a = 1.2; a = int(a); print(type(a))

<class 'int'>


In [20]:
a = '123'; print(type(a)); print(a[1])

<class 'str'>
2


List variables can be operated with indexes, and are mutable.

In [21]:
a = '123'; a = list(a); print(type(a)); print(a); print(a[2])

<class 'list'>
['1', '2', '3']
3


In [1]:
a = [1,'2', [3, '4']]; print(type(a)); print(a[0]); print(a[1]); print(a[2]) #lists can be nested

<class 'list'>
1
2
[3, '4']


Tuple variables share most properties with list variables, but are immutable.

In [23]:
a = (1,'2', [3, '4']); print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'tuple'>
1
2
[3, '4']


## Dictionary type associates two values with relation of 
### key(must be immutable object) : value

In [4]:
a =	{"a": "apple", "b": "orange", "c": 2014}
print(type(a))
print(a["a"])

<class 'dict'>
apple


In [5]:
a=[(1,2,3), (3,8,0)]
print(type(a))
a

<class 'list'>


[(1, 2, 3), (3, 8, 0)]

## Import modules by using import ~~ (from ~~ ) as ~~ syntax. 

In [6]:
import numpy as np
b = np.array(a)
print(b)
print(type(b))

[[1 2 3]
 [3 8 0]]
<class 'numpy.ndarray'>


Array objects are different from matrixes. Even though its form is generally the same.

In [7]:
print(b*b)

[[ 1  4  9]
 [ 9 64  0]]


Multiplication of arrays is element-wise.

Matrixes are availble as a class from numpy, and numpy.matrix(some_variable - list or arrays) can be used.

In [9]:
c = np.matrix(b)
print(c)
print(type(c))

[[1 2 3]
 [3 8 0]]
<class 'numpy.matrixlib.defmatrix.matrix'>


General multiplication rule for matrixes need to be followed for matrix type objects.

In [10]:
c*c

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

### .T method can be used for transposing matrixes

In [32]:
c*c.T

matrix([[14, 19],
        [19, 73]])